language: ruby
rvm:
  - 2.2.1
services:
  - postgresql
env:
  - RAILS_ENV=test
bundler_args: --jobs=3 --retry=3 --deployment --without development production
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:create db:migrate
addons:
  postgresql: "9.4"

# whitelist
branches:
  only:
    - master
notifications:
  email: false

deploy:
  provider: heroku
  api_key: 5e33963b-7c2b-4d9e-abd4-885b4e13009f
  app: timesheet-manager
  on:
    branch: master