language: ruby
rvm:
  - 2.2.1
services:
  - postgresql
env:
  - RAILS_ENV=test
bundler_args: --jobs=3 --retry=3 --deployment --without development production
before_script:
  - bundle exec rake db:create db:migrate db:seed
addons:
  postgresql: "9.4"
